language: node_js
node_js:
  - "8.10"
install:
  - npm install
  - npm run build
  - npm prune --production
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id:
    secure: fnQrxuVaEYFCaEY/Sr3hGskV/mvsRawi4TNt4BUm0mviPPAA/jeuWCQ7piVS4DHCJEH6Umxsag6VLXuVZyPL7pNwbDEULJdpjX0CWV62idfzOYqv6SV6YLvus5LfVTJOMxvmeq6yqgR2ud2r6nWtfBlpA60X1jtAFLbqbp6cGwtmF2+lJex1nt5Js7AbvjQyIdBQ+3OjOu0ZMNfLteB0fyfK2JQ8yinz7QY3rWx0cqrx4HYPhEc9rgznjjy5mmDUv1bO5bOBXCkGZCLaLfY3P4iieEDlTQDqlL7f/TYusIYH0S2FwnNEfR5YyEcYuadL8NifFuVIYIWv24VtH5jkFLepME37jRaVK5YvDr/sTMU0WB3V87+5humgVbtpU04AdzNgjcaQ8c0qujlaXd8ivkVZZnrPz8DkujAcEvDsdrNHZyW82qe1ggBG2zG3qS/Xn6Z/4E3uK3PbQO6foqsvtsrt7qml9zU3ovY7+oA2t9nhfvJiZ7EkVz21fNbYRk7M4xkXWHoTOIwkAhWiFC2WBhRRaGKHX5iF7K79H4ncIKPbY6RnOnDOL8QFxIfF/ePvmSHa7CaBBKMgHK8llgpTBySFCcLPXi07YWho7opHkjK+VERkGm0Fm/S55nqBcQR2wsnT2AS8NxnkIJXVR58v70xoNayoV9lot6WUBBZSrRE=
  secret_access_key:
    secure: s5BbYxI9IkdgbuHj6NmeCAokj+pykt9/Pt1rg7JYNgjUlHkxIzEfBHOytPGuneAz9ban6Sa0XVaoDWpYU+Fdnej+V/ASEVjMFdLzgaV8LTpZwPXWs5X65TlxH6Qh4dteHnkBEjMHIqVarZVnJdhCUhHFRDHEKheYRKYOn1RReVI+iJecJZmMr0snqBNS1c6sQYskoUrV/usg2XK9m86vXs877cUf3mRDufiF8yixEr46DXNdsiMlZ+VKxcCUdVksyF53qOfyRzi++miPhjrMeBvCm7FYZOgtd93T+wiVl/7IQercdVHSs+ePX/xA+ra4bvAgJZYTFWpBN/zBbPPix5kufO6tB3vj0OE6SZVOhBqTkzGSsVqgv+K4KiVElKtOlGBx7xpzMcWUXCXu8aHM0V0hOfk2GhWT/B9MZyLmBSK2NQSz8YPkRkN/oNnjW/xY3OyQ16AawF/xklBlcxpkOphLsqj5Afb+hITNNh4R38jjxrKlLqR+R7YvN65GBB03CaP3wqcYkggEDWTh+Qg3yk0VVsXkbtmHo2KLVl+f69bdivLI5sHOB4BuyoiQQpBA+4QJ4OuK9b2ErQaN6RFHMNuDG7fVyjGQEp6D0SlzDKuVsAipVNMxBlbhP8sEXuP53bGFSGQOb0CRDQK0hw3r+CU7k9QRRd91U+R+r7ZTXnI=
  region: us-east-1
  app: BoatyFrontend
  env: Boatyfrontend-env
  bucket_name: elasticbeanstalk-us-east-1-076182840641
